spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true

  flyway:
    clean-disabled: false

logging:
  level:
    "[com.poketeambuilder]": DEBUG
    "[org.springframework.web]": DEBUG
