spring:
  docker:
    compose:
      enabled: false

  jpa:
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

  flyway:
    clean-disabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    "[com.poketeambuilder]": DEBUG
    "[org.springframework.web]": DEBUG
